### ISSUE TITLE
3.3.1 Release?

### ISSUE THREAD

**Issue by ahundt** [cmake-basis/BASIS#615]
@schuhschuh Thanks for merging those changes! Seems things have been pretty stable over the last 9 months aside from the various bug fixes. Do you think you could use the current master for a 3.3.1 release? (or 3.4.0)

**Comment by schuhschuh** [comment]
Don't think this will happen within the next 3-4 months. Currently writing up my PhD thesis...

**Comment by ahundt** [comment]
Cool! Good luck :-) you're ahead of me I'm finishing classes at the end of this semester haha. 

Sorry for the confusion, can you do a point release bump with the code as-is in master consisting of the 40 most recent commits https://github.com/cmake-basis/BASIS/compare/v3.3.0...master? No need to implement any of the planned "milestone" changes! Hopefully that just takes a few minutes?

**Comment by ahundt** [comment]
Thanks!
