### ISSUE TITLE
How do you want to solve this issue?

### ISSUE THREAD

**Issue by kayhan-batmanghelich** [cmake-basis/BASIS#622]
Happy Birthday :)

ps: Total abuse of github issue :)

**Comment by schuhschuh** [comment]
Hey @kayhan-batmanghelich! Thank you! That's indeed a unique way of sending your wishes ;-)

Hm, so how am I gonna solve this one. Guess as every human I've observed so far is aging, I'd say that was meant by design and not a fault?
