### ISSUE TITLE
Unable to compile BASIS in windows 10

### ISSUE THREAD

**Issue by srini2174** [cmake-basis/BASIS#626]
I am trying to compile BASIS 3.3.0 in windows 10.  I get the following error

[5/9  55%] Linking CXX static library lib\libutilities.a
[6/9  66%] Building CXX object src/utilities/cxx/CMakeFiles/testmain.dir/test_main.cxx.obj
FAILED: src/utilities/cxx/CMakeFiles/testmain.dir/test_main.cxx.obj 
C:\ProgramFiles\mingw64-71\bin\g++.exe  -DHAVE_Perl -I../src -I../include -Iinclude -O3 -DNDEBUG -MD -MT src/utilities/cxx/CMakeFiles/testmain.dir/test_main.cxx.obj -MF src\utilities\cxx\CMakeFiles\testmain.dir\test_main.cxx.obj.d -o src/utilities/cxx/CMakeFiles/testmain.dir/test_main.cxx.obj -c ../src/utilities/cxx/test_main.cxx
In file included from ../include/basis/test.h:54:0,
                 from ../src/utilities/cxx/test_main.cxx:42:
../include/basis/gtest/gtest.h:3060:3: error: 'AutoHandle' does not name a type; did you mean 'mutable'?
   AutoHandle thread_;
   ^~~~~~~~~~
   mutable
[7/9  77%] Building CXX object src/utilities/cxx/CMakeFiles/testlib.dir/test.cxx.obj
FAILED: src/utilities/cxx/CMakeFiles/testlib.dir/test.cxx.obj

I tried using mingw64 - version 5.4.  The cmake version is 3.9.1.  The error message with this version is posted above.

I have also tried using Visual studio 2017 & mingw64-version 7.1 but I am unable to get it to compile with very similar error.

Thanks in advance for any help

**Comment by srini2174** [comment]
Maybe this can help. https://github.com/google/googletest/issues/606

**Comment by srini2174** [comment]
Any help please.

**Comment by schuhschuh** [comment]
This issue should be fixed now by #634. Please reopen if issue persists. See also #631.
