### ISSUE TITLE
MSVC Pthread issue

### ISSUE THREAD

**Issue by Foadsf** [cmake-basis/BASIS#632]
Following [this SO question](https://stackoverflow.com/q/60747538/4999991), running the CMake command:

    cmake -DCMAKE_INSTALL_PREFIX:PATH=/home/foobar/local -DBUILD_APPLICATIONS:BOOL=ON -DBUILD_EXAMPLE:BOOL=ON .. -G "Visual Studio 15 2017 Win64"

leads to:

> -- Looking for pthread.h - not found

I tried copy-pasting files `FindThreads.cmake`, `FindPackageHandleStandardArgs.cmake`, and `FindPackageMessage.cmake` from [here](https://github.com/Kitware/CMake/tree/master/Modules) with no avail. Though the compiling-installing command 

    cmake --build . --config release --target install

seems to be working:

**Comment by schuhschuh** [comment]
The `pthreads` library is for Unix systems only. You wouldn't use it on Windows for multithreading. Hence, the "not found" message is likely just an FYI, not an error. As you say compilation succeeds, and presumably executables work as expected, would you say this is still an actual issue requiring some fix?

**Comment by Foadsf** [comment]
@schuhschuh how about using:

~~~c
#ifdef _WIN32
#include <windows.h>
#else
#include <pthread.h>
#endif
~~~

**Comment by schuhschuh** [comment]
Given that compllation succeeds, this should be the case in code. Note that
the status message is from CMake's Find module, simply reporting what it
has or hasn't found installed on your system. It's not a C++ compiler
message.

**Comment by Foadsf** [comment]
@schuhschuh Then I think we should modify the CMake scripts to do not check pthread if on Windows or MSVC. can we do that?

**Comment by schuhschuh** [comment]
Note that BASIS itself does not check for pthreads itself, but a "Threads" library (also a valid query on Windows). It is CMake's official [FindThreads.cmake](https://github.com/Kitware/CMake/blob/master/Modules/FindThreads.cmake) module which emits this informational message. You may want to discuss this with the CMake developers themselves if you believe the behavior of FindThreads should be modified. IMHO This is normal behavior.

What can be done is to modify the CMake command `find_package(Threads)` in `config/Settings.cmake` to use `QUIET` flat. This will silence messages from FindThreads with the downside of course that there is no feedback on whether or not a threading library was found.
